### PR TITLE
Request maintainer status for @ThatsMrTalbot

### PR DESCRIPTION
**Pull request by ThatsMrTalbot**
Further to our conversation during standup  and following the steps laid out in the GOVERNANCE.md I am requesting maintainer status:

> Any existing Approver can become a cert-manager maintainer. Maintainers should be proficient in Go; have expertise in at least one of the domains (Kubernetes, PKI, ACME); have the time and ability to meet the maintainer expectations above; and demonstrate the ability to work with the existing maintainers and project processes.
> 
> To become a maintainer, start by expressing interest to existing maintainers. Existing maintainers will then ask you to demonstrate the qualifications above by contributing PRs, doing code reviews, and other such tasks under their guidance. After several months of working together, maintainers will decide whether to grant maintainer status.

As part of my Venafi role part of my responsibilities is to contribute to cert-manager, so I have the time and availablity to meet the maintainer expectations. As for my proficiency, I hope my work with you in the last 5 months has shown this.

Based on the governance document it was not clear how "maintainers will decide whether to grant maintainer status" so it was decided on the call that we would use "lazy consensus" as described in the "Maintainer Decision-Making" documentation. This can be done as comments on this PR for visibility.

### CODE REVIEW

**Comment by SgtCoDFish** [comment]
Fully support this; Adam does a lot of good work! He's been heavily involved in the makefile modules stuff for example.

He's also paid to work on cert-manager at least part of the time - it makes sense for him to be able to do things like releases. He volunteered to do the release of 1.15 and more support with releases is always welcome!

Full disclosure: Adam also works at Venafi so I'm not entirely impartial. I would support his maintainership if I were at any company but it's important to be transparent on that.

**Comment by maelvls** [comment]
(Disclaimer: Adam is my colleague)

Adam has been improving many parts of the cert-manager project and has been reviewing and falicitating contributions in [in 246 PRs](https://github.com/search?q=org%3Acert-manager+involves%3AThatsMrTalbot+-author%3AThatsMrTalbot&type=pullrequests) among 33 projects (!!!) and has been instrumental to projects such as the Makefile Modules project.

Adam has also been helping [with issues](https://github.com/search?q=org%3Acert-manager+involves%3AThatsMrTalbot+-author%3AThatsMrTalbot&type=issues), and has also helped in the #cert-manager channel.

I am in favor of adding Adam as a maintainer!

**Comment by inteon** [comment]
Thanks everyone for voting, we reached the end of the lazy consensus period (https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1714386002098739).
The following maintainers are in favor of the change:
- @maelvls
- @irbekrm
- @SgtCoDFish
- @jakexks
- @wallrj
- @inteon
There were no votes against.

👍 @ThatsMrTalbot **has been accepted** as a new maintainer.

Thanks for your past and future contributions to the cert-manager project, @ThatsMrTalbot.

/approve
/lgtm

**Comment by SgtCoDFish** [comment]
PSA: I've added Adam to the cert-manager-maintainers and cert-manager-security mailing lists.

**Comment by maelvls** [comment]
To be done next (somewhat documented in https://github.com/cert-manager/infrastructure):

- [ ] Add Adam Talbot <adam.talbot@venafi.com> to https://github.com/cncf/foundation/blob/main/project-maintainers.csv
- [ ] Set @ThatsMrTalbot to "Admin" in the cert-manager GitHub org
- [ ] Add Adam to the @cert-manager-maintainers group on the Kubernetes Slack → https://github.com/kubernetes/community/pull/7368
- [ ] Request CNCF service desk to add adam.talbot@venafi.com to the maintainers
- [ ] Add adam.talbot@venafi.com to cert-manager-security@googlegroups.com
- [ ] Add adam.talbot@venafi.com to cert-manager-maintainers@googlegroups.com 


Btw I found that https://github.com/cncf/toc/blob/main/docs/PROJECTS.csv still says that cert-manager is Sandbox 😅

**Comment by SgtCoDFish** [comment]
I can confirm @ThatsMrTalbot is an "owner" (equivalent to "admin") on the GitHub org 👍

**Comment by maelvls** [comment]
@ThatsMrTalbot I've just noticed that you aren't "Owner" in the YouTube Brand Account https://myaccount.google.com/brandaccounts/101688634375640008002/view. Each maintainer should have access to it. I've added you there so you can upload videos to the cert-manager channel if you ever need.

**Pull request merged**
